### PR TITLE
Tune pre-selection (v2)

### PR DESCRIPTION
**Pull request by sarafiorendi**
Change the pre-selection cuts, starting from Arabella's proposal in #42, plus some changes discussed in the PR conversation or discussed verbally.
Please comment if I missed something.

### CODE REVIEW

**Comment by gkaratha** [comment]
Hi,

What is the efficiency for that? Is any plot/study circulated and i missed it ? ( sorry if i did miss it)

**Comment by sarafiorendi** [comment]
basically the cuts are those from your WP80, with these differences:
- track pT 0.7 instead of 0.8 GeV
- dR > 0.03 between the two leptons

**Comment by gkaratha** [comment]
Hi Sara,
My question was more on that:
     lep1Selection = cms.string('pt > 1.5 && userFloat("unBiased") >= 4'),
In my study it was on 3.

**Comment by sarafiorendi** [comment]
ah, sorry that is my typo, I meant to use your same selection. Will fix it now.

**Comment by mverzett** [comment]
@gkaratha, any further comments? Otherwise we can merge for me.

**Pull request merged**
