### PR TITLE
Update README recipe to use 2019Aug07 model for electron ID

### PR DESCRIPTION
**Pull request by bainbrid**
Recipe requires testing before merging this PR!

Should give ~5-10% gain in electron efficiency for same WP w.r.t. 2018Jun28 model.

@sarafiorendi @gkaratha @amartelli @mverzett

### CODE REVIEW

**Comment by amartelli** [comment]
Dear all, I run the validation in the test folder and the results are here:
https://amartell.web.cern.ch/amartell/Analysis/BParking/validatePR74/

it's the first time I run it, so I don't have a previous reference, but I did not find any obvious error in my procedure. Anyway, I find it surprising that on DATA the timing is reduced for Electrons from 87% to 84%. Is it expected with this PR? Or should the timing be more or less unchanged?
It could also be due to the validation being run on 1000 events... what do you think?

**Comment by sarafiorendi** [comment]
ciao Arabella, 
I also find strange that you don't see any difference in the Electron_mvaId distribution between old and new (if there are differences the validation code should produce the specific distribution, and also in the [log](https://amartell.web.cern.ch/amartell/Analysis/BParking/validatePR74/validation_data/validation_log.html) we should have an appropriate printout).
I think that since the validation script only checks out the PR to the BParkingNano repo, and not to the CMSSW one, probably you are running twice the same code.

**Comment by bainbrid** [comment]
Hi arabella,

The recipe was updated: https://github.com/CMSBParking/BParkingNANO/blob/eb54f99ae0f488ad2342bce7020ae31dc42c7a6b/README.md

Did you follow the instructions for the 2019Aug07 model?

**Comment by amartelli** [comment]
Hi, I simply run the validation package as it is. So I agree with Sara... I will try the validation by hand.

**Comment by amartelli** [comment]
Here the new validation https://amartell.web.cern.ch/amartell/Analysis/BParking/validatePR74/
size unchanged and the difference in the mvaID is correctly spotted.
The CPU/evt time is x1.5 for data and almost the same for mc

I also notice in the validation_log for data only BToKsEE_fit_massErr--> CONTAINS INFs/NANs!
this is there since a while and absent for MC.
I'll give a quick check

**Comment by amartelli** [comment]
@bainbrid 
I read it wrong and now corrected (thanks Sara) with this PR the total time is 1.5 faster on data.
The total number of events used for the validation is limited (1k), but does it seem reasonable to you?

**Comment by bainbrid** [comment]
@amartelli
Given the reduced model size, I think this makes sense ...

LowPtElectrons.2019Jun28:
-rw-r--r--. 1 bainbrid zh 52969001 Aug  5 18:09 RunII_Autumn18_LowPtElectrons_mva_id.xml.gz

LowPtElectrons.2019Aug07:
-rw-r--r--. 1 bainbrid zh 18939927 Dec 12 20:51 RunII_Autumn18_LowPtElectrons_mva_id.xml.gz

Cheers
rob

**Comment by amartelli** [comment]
ok thanks for the check.

For me all this looks fine and could be merged.

**Pull request merged**
