### PR TITLE
Update input collections

### PR DESCRIPTION
**Pull request by gkaratha**
Hi all,

Perhaps @amartelli  wants to look at this and please give a review / comment. Essentially instead of making a huge PR i broke it in two. Here is the first part - inputs
To summarize:
   - I rewrote the the cleaning with respect to triggering muon(s) for all inputs (muons, tracks, electrons) -> cleaner and faster
   - Made the electron merger to also cut and put BDT values so we need to loop only once instead of multiple times
   - All input objects that pass the cuts are labelled: Selected<NameOfObject>
   - Removed the two selections from track merger. If we are sure that K in tag objects are within certain DR from trg muon we can uncomment it
   - Fixed the addAsDaughter in composite candidate. Now the composite candidate has correct pT, eta, phi without "hackering it" as daughter. The candidate itself is added as additional Cand. I need to check that this works in later steps though.
    - Checked on 1k evts that results are fine
    - Measured time and size wrt to the flat ntuple
   - Fixed all the relevant cffs
   - Added comments questions in line so anyone can follow
If there are comments let me know

Best,
George

### CODE REVIEW

**Comment by sarafiorendi** [comment]
hi @gkaratha,
sorry it seems that your PR is introducing the file TrackMerger.cc and removing TrackProducer.cc, which was already done when merging with PR#10. Maybe a rebase of yours is needed?

**Comment by gkaratha** [comment]
Hi @sarafiorendi 

Well I took Arabella's pr before was merged. Can this be the reason? So just "git rebase" will fix it?

Thanks for the help,
George

**Comment by mverzett** [comment]
@gkaratha a rebase should fix it, can you please try?

**Comment by gkaratha** [comment]
Hi @mverzett ,

I already tried yesterday but i managed to remove my files instead... I will try again with different (hopefully) more successful approach.

**Pull request closed without merging**
