### PR TITLE
adding 3D vertex information

### PR DESCRIPTION
**Pull request by gitytakahas**

### CODE REVIEW

**Comment by amartelli** [comment]
Hi @gitytakahas, 
do I understand correctly the logic/changes of this PR ?
- the core of the addition are the following variables
vtx_3d_lip, vtx_3d_lips, vtx_3d_pvip, vtx_3d_pvips, vtx_3d_fl3d, vtx_3d_fls3d, vtx_3d_alpha
- these are computed for the B candidate using the B_refit_vertex (as SV) and the primary vertex with smallest lip (closest in z, I would say) wrt the ll_refit_vtx (as PV)

- do you think that the relevant PV is the closest in Z to the B_refit_vtx ? 
what we are saving so far is the PV from 
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
with cfg https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/vertices_cff.py

- It's not obvious for me to  see how the PV closest in z to the B_refit_vtx should be the favourite.
At the same time, the standard criteria (highest sum pt) might not be optimal as well.
Is this the common choice for B physics analysis?

- If we want to use as PV the one chosen by your PR, it's probably useful to save a vertexTable  also of the vertex chosen, so that we can use it later on 
(for example to compute the momentum balance à la LHCb we need a PV, and we can test with all the PV saved in the nano.

thanks for any clarification

**Comment by gitytakahas** [comment]
Hi @amartelli 

Thanks for the query. Before replying to your question, as I sent an email before, specifying the bb production vertex and use 3D information (instead of 2D as you are using) won't help that much in terms of signal/BG discrimination. So, unless you think necessary or you want to try, you don't need to merge this PR. 

Please see my answers below;

> * the core of the addition are the following variables
>   vtx_3d_lip, vtx_3d_lips, vtx_3d_pvip, vtx_3d_pvips, vtx_3d_fl3d, vtx_3d_fls3d, vtx_3d_alpha

Right 

> * these are computed for the B candidate using the B_refit_vertex (as SV) and the primary vertex with smallest lip (closest in z, I would say) wrt the ll_refit_vtx (as PV)

Right 

> * do you think that the relevant PV is the closest in Z to the B_refit_vtx ?
>   what we are saving so far is the PV from
>   https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
>   with cfg https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/vertices_cff.py

According to my study, by extrapolating back di-lepton trajectory to the beam line and find the vertex closest in z, you can find the correct vertex with 94% of the time (I checked this using Bc->J/psi tau nu MC). You can do the same thing by extrapolating B trajectory, but there should be little gain by doing so. Furthermore, by just using di-lepton, you can use the same method for R(K) and R(K*). 

> * It's not obvious for me to  see how the PV closest in z to the B_refit_vtx should be the favourite.
>   At the same time, the standard criteria (highest sum pt) might not be optimal as well.
>   Is this the common choice for B physics analysis?

PV with the highest sum pt^2 is not optimal for most of the B-physics analyses,
as Bs are relatively light and cannot always rank in the first position in terms of sum pt^2.

But this is something you can easily check by using your signal MC sample. 

> * If we want to use as PV the one chosen by your PR, it's probably useful to save a vertexTable  also of the vertex chosen, so that we can use it later on
>   (for example to compute the momentum balance à la LHCb we need a PV, and we can test with all the PV saved in the nano.
> 
> thanks for any clarification

**Comment by amartelli** [comment]
@gitytakahas thanks a lot for the further info.
So, we now need a primary vertex to build the "momentum balance" as LHCb did, that seems to help the signal vs bkg discrimination.
See for example slides 2,3 of https://indico.cern.ch/event/890357/contributions/3754999/attachments/1989459/3316366/update_18Feb_v2.pdf

So, since the vertex identified by your PR is ok ~94% cases, while the PV with sum pT^2 is definitely not the best, I am in favour of adding this.
@sarafiorendi what do you think?

In case, Yuta, do you mind rebasing the PR to solve the conflicts and also add a vertexTable
for the chosen vertex (or at least to add vtx_x, vtx_y, vtx_z for this) ?

**Comment by gitytakahas** [comment]
@amartelli 

Sure, I'll try to do this tomorrow - that being said, I'm not familiar with the "VertexTable" part. So, I might ask you to implement it based on the PR that I'll make tomorrow, if that's fine with you (or I can at least add vtx_x, y, z)

**Comment by gitytakahas** [comment]
So maybe, we can close this PR for now, and instead I'll make new one tomorrow.

**Comment by amartelli** [comment]
I think  vtx_x, y, z are enough 
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/PhysicsTools/NanoAOD/python/vertices_cff.py#L29-L33

thanks a lot

**Pull request closed without merging**
