### PR TITLE
WIP: match tracks to low-pT electrons

### PR DESCRIPTION
**Pull request by bainbrid**
@ottolau @gkaratha @amartelli @crovelli 

I checked on small data and MC samples using run_nano_cfg.py.
Results reasonable, but needs more thorough testing.

### CODE REVIEW

**Comment by bainbrid** [comment]
Hi @ottolau if you have time to test this, it would be appreciated. Then we can merge.

**Comment by ottolau** [comment]
Hi all,

Here is the validation [https://cernbox.cern.ch/index.php/s/w2FVskLM8QtVonQ](url). It looks good to me.

Best,
Otto

**Comment by bainbrid** [comment]
@ottolau shall I merge?

**Comment by ottolau** [comment]
Just merged

**Pull request merged**
