### PR TITLE
Save simple track-based isolation 

### PR DESCRIPTION
**Pull request by sarafiorendi**
First version of track-based isolation is added for the Kll channel.
It is calculated for
- each final state particle (kaon, lep1, lep2)
- the B candidate
in 2 dR cones, dR<0.3 and dR<0.4.
Both version are saved for now, since further studies are needed.
Only tracks with pT>0.7 GeV are considered, and tracks that match either the kaon or one of the leptons are discarded.
Further simple requirements could be added in the cfg.

Here some distributions for the Kee (after preselection, no distinction between PF and lowPt eles, all candidates per event are kept)
https://fiorendi.web.cern.ch/fiorendi/parking/framework_validation/isolation/Kee/
and Kmumu
https://fiorendi.web.cern.ch/fiorendi/parking/framework_validation/isolation/Kmm/
Signal is from B→Kee or Kmumu MC, for candidates in the B mass window matched to GEN ones. Background is from data candidates outside the B mass region.
From a quick local test, the added timing is minimal, but I will verify this again with the "validation" package and post the results.

If you agree with the current implementation, I can add the same iso variables to the K*ll producer.

### CODE REVIEW

**Comment by sarafiorendi** [comment]
p.s. I'm not sure why git shows differences also in the samples.yml file, since in the master branch it should be already updated as the one in this branch.

**Comment by amartelli** [comment]
The code seem ok. 
You start from the full track (and lost track) collections, instead of the filtered track collection that we produce before building the B cand.
The filtered have in addition the dZ wrt trigger muon ( <1) and dR (> 0.03).
As you say, if the added timing is minimal with all tracks considered, it's OK!

From the plots - signal vs bkg - indeed this seem useful.

Ok to merge for me

**Comment by sarafiorendi** [comment]
Yes I start from the full tracks so that we are independent from the requirement on the signal tracks.
thanks!

**Comment by amartelli** [comment]
merging for December 2019 ntuple production

**Pull request merged**
