### PR TITLE
Build object transient track and make them available to the event

### PR DESCRIPTION
**Pull request by sarafiorendi**
Modified code preparing electron, track and muon inputs to also build their transientTracks and have the available during the event processing.
It is not possible though to save TransientTrackCollections in the output file, so this is taken into account in case "FullReco" is requested.

### CODE REVIEW

**Comment by mverzett** [comment]
[Validation](https://mverzett.web.cern.ch/mverzett/bph_plots/FAKE_CI/PR23/) is OK no changes spotted

**Comment by gkaratha** [comment]
@mverzett Why the timing is different with and without this PR ?

**Comment by mverzett** [comment]
There could be multiple reasons, I'm not sure which one is the right one:
   * There are fluctuations in the CPU usage, we are not running on dedicated machines therefore the timing will always fluctuate
   * The PR in the end does something, but does not change the logic
   * The large change in the Wall time may be due to some initialization, i.e. retrieving the magnetic field, but it's really hard to tell.

The purpose of the timing plot is mostly to have ballpark measures and understand where most of the time is spent, it definitely does not have a 1% accuracy (maybe 20%)

**Comment by sarafiorendi** [comment]
Also, with this PR we are computing the transientTracks for electrons and muons, which was not done before in the master. And this is supposed to increase the timing.

**Comment by gkaratha** [comment]
well the tracks were reduced more than 40% absolute value while the I/O and table remained almost similar. I suppose that the "load" part is out of the question otherwise it would be everywhere

**Comment by mverzett** [comment]
@gkaratha you are right, I checked the logs and I do not have a clear explanation for this. I observed something similar in the past (#17) in that case in comparing a 100 and a 1000 events, with the same code. I did not have time to look into the reason for that yet though.

**Comment by sarafiorendi** [comment]
I've done some checks and what I understand is that the reduction in timing of the track module is due to the fact the handle to the MagneticField is already done inside muonTrgSelector now, and therefore it is not done/is simply recalled (I don't know the details) in the TrackMerger. 

The numbers are [here](https://fiorendi.web.cern.ch/fiorendi/parking/check_timing_PR23.txt)

**Comment by mverzett** [comment]
@sarafiorendi thanks for looking into it and finding the cause of the timing!

**Pull request merged**
