### PR TITLE
Phill

### PR DESCRIPTION
**Pull request by ottolau**
Dear all,

phi ll reconstruction. I just copy everything from George's K* ll code and change them to phi ll. The PhiBuilder is copied from KstarBuilder, we may consider merging them later.

Best,
Otto

### CODE REVIEW

**Comment by gkaratha** [comment]
Dear Otto,

Thanks for the PR. To my mind i think that PhiBuilder is redundant. It would be better a more generic builder, like the dileptonBuilder, that would fit tracks at least for start. That would also better when more channels are included (eg D0 etc). Otherwise  we will end up copying the same file continuously.  @mverzett @sarafiorendi @amartelli opinions?

**Comment by mverzett** [comment]
@gkaratha indeed I agree with you, if the only difference is the track mass assumption it would be better to have it either as configurable parameter of a DiTrackBuilder or as a constant template argument and then only have different specializations.

**Comment by gkaratha** [comment]
HI @mverzett ,

I totally agree i had the same thing in mind :) 

Best,
George

**Comment by ottolau** [comment]
Yes I agree, but we want to get the phi part as well in the coming ntuple production. Do you think we can stick to this one first and them switch to DiTrackBuilder afterward? Thanks!

**Comment by amartelli** [comment]
Hi Otto, all, the flexibility of the code allows to launch a production for a single final state, like the Phi part. So I don't see it a problem to launch it soon when the code is ready.
At the same time, this code should undergo the same validation procedure used for the rest and waiting for this will delay a production on the rest - that could start now.

So, how about we launch on K, K* data / MC and in parallel keep working on the phi channel and launch it as soon as it is ready?

**Comment by sarafiorendi** [comment]
Hi Arabella, all, 
I would also be in favour of starting a new ntuple production now with K and K*, and submit Bs once we have the code integrated and validated.

**Comment by mverzett** [comment]
> Hi Arabella, all,
> I would also be in favour of starting a new ntuple production now with K and K*, and submit Bs once we have the code integrated and validated.

+1 for me as well

**Comment by ottolau** [comment]
Sure we can start K/K* first and then produce only phi later

**Comment by ottolau** [comment]
Dear all,

I updated the code so that we have a DiTrackBuilder for both K* and phi.

Best,
Otto

**Comment by sarafiorendi** [comment]
Hi @ottolau,
sorry for the long delay.
Could you update the PR so that files that already in the repo (e.g. BToKstarLLBuilder.cc) does not appear as new additions? 
Also, if I understand correctly, both PhiBuilder and KstarBuilder would be replaced by DiTrackBuilder, correct? if yes, can you clean those files as well?
thanks!

**Comment by gkaratha** [comment]
Hi @ottolau ,

Perhaps I wrote a comment under a different PR, so sorry for that! I think it would be better, since we are not going to submit this week to have an update on how your ID affects signal and Bkg in Data (and MC). Also to define the WP (Maybe 90% is already hard for us). Could you think you can manage by tomorrow? Thanks.

Best,
George

**Comment by ottolau** [comment]
Dear all,

The simple rebase doesn't work so I just open a new pull request.

Best,
Otto

**Comment by amartelli** [comment]
Hi @ottolau, so can this PR simply be closed, as replaced by #70 ?

please confirm or close. thanks!

**Comment by ottolau** [comment]
Hi @amartelli, yes, thanks for reminding me!

**Pull request closed without merging**
