### PR TITLE
A new recipe with final ID model (2020Sept15) and regression

### PR DESCRIPTION
**Pull request by bainbrid**
Please see the README.md file [here](https://github.com/CMSBParking/BParkingNANO/blob/e912191fbc9589107ed7c1727a8d974636456a28/README.md).

Please test before we merge!

@crovelli @gkaratha @ottolau @amartelli

### CODE REVIEW

**Comment by bainbrid** [comment]
@crovelli @gkaratha @ottolau @amartelli @sarafiorendi 

1) I've removed the 4 GB RAM requirement from the production/submit_on_crab.py file (at Chiara's request)
2) The recipe described by the README.md has been [updated to include the depth15 model by default](https://github.com/CMSBParking/RecoEgamma-ElectronIdentification/commit/f8e854795d2d244c3a871e955ea119040a4a7943).

If you have already installed using this recipe and do not wish to reinstall from scratch, it's probably sufficient to:
```
cd $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data/LowPtElectrons/
git pull 
cd -
mkdir -p $CMSSW_BASE/src/RecoEgamma/ElectronIdentification/data/LowPtElectrons
cp $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data/LowPtElectrons/LowPtElectrons_ID_2020Sept15.root $CMSSW_BASE/src/RecoEgamma/ElectronIdentification/data/LowPtElectrons
```
Please check carefully that the .root file updates!

**Please feel free to merge and adopt.**

**Comment by bainbrid** [comment]
Now include bug fixes from Francesca: [here](https://github.com/CMSBParking/BParkingNANO/blob/57d7763bc72643f91900e732330b4a76f5ab3791/README.md) and [here](https://github.com/bainbrid/BParkingNANO/pull/1/commits/11f176785d7894ba05891e79af2b671a5861d954).

Either start from a fresh install, or do the following:

1)
```
cd $CMSSW_BASE/src
git add remote CMSBParking git@github.com:CMSBParking/cmssw.git
git pull CMSBParking from-CMSSW_10_2_15_2020Sept15
```
2)
```
cd $CMSSW_BASE/src/PhysicsTools/BParkingNano
git remote add bainbrid git@github.com:bainbrid/BParkingNANO.git
git pull bainbrid master
```

Probably safest to do a fresh install ...

**Comment by bainbrid** [comment]
@cavalari

**Comment by gkaratha** [comment]
Hi,

Trying the commands in the new readme, the code will compile but not run. For some reason seems that now lowPtGsfElectronIDExtra_cff.py is missing. Unless if i missed a command. Can you please verify that ?

**Comment by bainbrid** [comment]
Hi @gkaratha you tried exactly [this](https://github.com/CMSBParking/BParkingNANO/blob/e912191fbc9589107ed7c1727a8d974636456a28/README.md) recipe?
(This is the recipe in this PR - I'll add the link at the top of the page to be explicit.)

I see the file [here](https://github.com/CMSBParking/cmssw/blob/from-CMSSW_10_2_15_2020Sept15/RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronIDExtra_cff.py).

**Comment by gkaratha** [comment]
Hi @bainbrid, Indeed it was my mistake. Accidently I put some instructions from the previous PR. I checked, everything is ok and i will merge it

**Pull request merged**
