### PR TITLE
Modify transientTrack building for ele

### PR DESCRIPTION
**Pull request by sarafiorendi**
Making use of the code provided by Arabella, which is now included in the CMSBParking:GsfTransientTracks branch of cmssw.
Instructions are updated accordingly.

### CODE REVIEW

**Comment by amartelli** [comment]
seems ok!

**Comment by mverzett** [comment]
Looks good to me as well, testing now

**Comment by mverzett** [comment]
The merge-topic brings in a **LOT** of unwanted packages in `CMSSW_10_2_15`, can you fix it?

**Comment by mverzett** [comment]
Validation [here](https://mverzett.web.cern.ch/mverzett/bph_plots/FAKE_CI/PR38/)

**Pull request merged**
