### PR TITLE
sort electron collections for easier logic afterwords

### PR DESCRIPTION
**Pull request by amartelli**
Restore pt sorting of electron collection.
TransientTrack collection also sorted accordingly: check on isValid() has been removed, can be applied in the B candidate builder (if needed)

The option can be configured and currently is set to True

### CODE REVIEW

**Comment by mverzett** [comment]
Looks good to me. I would put it on hold until #24 is also finalised and then I would include the isValid check and the logic simplification in this PR as well.

Really minor comment: we should agree on the indentation schema and make a PR to make everything uniform and don't touch it :)

**Comment by mverzett** [comment]
Thinking again, if we change the logic downstream assuming the sorting it should not be configurable.

**Comment by amartelli** [comment]
Correct I agree, but we still have to implement muon+track+track (and also there, are we going to sort the muon+track collection?)
And in addition, we haven't tried the full chain with final selections. If the sorting becomes too much time consuming maybe we can remove it.
Can we leave the fix of all the configuration parameters (and the removal of this one in case) to the next stage?

**Comment by amartelli** [comment]
Concerning the indentation, I agree. And sorry but I did not resist. Can I propose to use scram build code-format ?

**Comment by mverzett** [comment]
Looks a good option to me :)

**Comment by sarafiorendi** [comment]
here the results of the validation against current master
https://fiorendi.web.cern.ch/fiorendi/parking/validate27_againstMaster/

**Comment by amartelli** [comment]
thanks for these checks. These seem very small fluctuations, the real change I see is in l1idx and l2idx that is expected. I agree with your conclusion

**Comment by mverzett** [comment]
Do we know where the differences are from? In principle the sorting should not change the histograms

**Comment by amartelli** [comment]
ok maybe we are looking at different hosts then, because for BToKEE_fit_pt for example, this is the comparison that I see...
https://fiorendi.web.cern.ch/fiorendi/parking/validate27_againstMaster/validation_data/BToKEE_fit_pt.png

**Comment by mverzett** [comment]
Checking manually one event that produce two slightly different sets of candidates I noticed that indeed the differences are minimal. In that case the cause is that the leptons are swapped and apparently the fit converges to slightly different values.
Given this I think there is no problem.

**Pull request merged**
